# Generated by Django 5.0.2 on 2024-02-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uavrental'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavrental',
            name='uav_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uavrental',
            name='user_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
