# Generated by Django 5.0.2 on 2024-02-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uavrental_uav_info_uavrental_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavrental',
            name='user_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
